// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMedicina.BackEnd.Model;

#nullable disable

namespace WebMedicina.BackEnd.Model.Migrations
{
    [DbContext(typeof(WebmedicinaContext))]
    [Migration("20231231174507_SeedMutacionYEpilepsia2")]
    partial class SeedMutacionYEpilepsia2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Aspnetuserrole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("aspnetuserroles", (string)null);
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.AspnetroleModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique();

                    b.ToTable("aspnetroles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "7d627f02-ae76-49f1-b0e4-36d46b8a51a0",
                            Name = "superAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "ccc2c28c-365d-4159-8f47-f2cce78d415c",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "273e5717-1493-46f6-9f5c-82f87a0fc3ef",
                            Name = "medico",
                            NormalizedName = "MEDICO"
                        });
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.AspnetroleclaimModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("aspnetroleclaims", (string)null);
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.AspnetuserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int(11)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasMaxLength(6)
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique();

                    b.ToTable("aspnetusers", (string)null);
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.Aspnetuserclaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("aspnetuserclaims", (string)null);
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.Aspnetuserlogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("aspnetuserlogins", (string)null);
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.AspnetusertokenModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0, 0 });

                    b.ToTable("aspnetusertokens", (string)null);
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.DatosEvoluEtapasLT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EtapaLTId")
                        .HasColumnType("int");

                    b.Property<int>("PacienteIdPaciente")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("EtapaLTId");

                    b.HasIndex("PacienteIdPaciente");

                    b.ToTable("DatosEvoluEtapasLTModel");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.EpilepsiaModel", b =>
                {
                    b.Property<int>("IdEpilepsia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idEpilepsia");

                    b.Property<DateTime>("FechaCreac")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaUltMod")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre")
                        .HasDefaultValueSql("''");

                    b.HasKey("IdEpilepsia")
                        .HasName("PRIMARY");

                    b.ToTable("Epilepsias");

                    b.HasData(
                        new
                        {
                            IdEpilepsia = 1,
                            FechaCreac = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            FechaUltMod = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Epilepsia1"
                        },
                        new
                        {
                            IdEpilepsia = 2,
                            FechaCreac = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            FechaUltMod = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Epilepsia2"
                        });
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.EtapaLT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreac")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaUltMod")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MedicoCreadorIdMedico")
                        .HasColumnType("int(11)");

                    b.Property<int>("MedicoUltModifIdMedico")
                        .HasColumnType("int(11)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MedicoCreadorIdMedico");

                    b.HasIndex("MedicoUltModifIdMedico");

                    b.ToTable("EtapaLTModel");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.EvolucionLT", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Confirmado")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("EtapasLTId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MedicoUltModifIdMedico")
                        .HasColumnType("int(11)");

                    b.HasKey("Id");

                    b.HasIndex("EtapasLTId");

                    b.HasIndex("MedicoUltModifIdMedico");

                    b.ToTable("EvolucionLTModels");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.FarmacosModel", b =>
                {
                    b.Property<int>("IdFarmaco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idFarmaco");

                    b.Property<DateTime>("FechaCreac")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaUltMod")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre")
                        .HasDefaultValueSql("''");

                    b.HasKey("IdFarmaco")
                        .HasName("PRIMARY");

                    b.ToTable("Farmacos");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.MedicosModel", b =>
                {
                    b.Property<int>("IdMedico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idMedico");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("apellidos");

                    b.Property<DateTime>("FechaCreac")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaNac")
                        .HasColumnType("datetime")
                        .HasColumnName("fechaNac");

                    b.Property<DateTime>("FechaUltMod")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NetuserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("netuserId")
                        .UseCollation("utf8mb4_general_ci");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("sexo")
                        .HasDefaultValueSql("''");

                    b.Property<string>("UserLogin")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("userLogin");

                    b.HasKey("IdMedico")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "UserLogin" }, "userLogin")
                        .IsUnique();

                    b.HasIndex(new[] { "NetuserId" }, "Índice 2");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.MedicospacienteModel", b =>
                {
                    b.Property<int>("IdMedPac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idMedPac");

                    b.Property<int>("IdMedico")
                        .HasColumnType("int(11)")
                        .HasColumnName("idMedico");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int(11)")
                        .HasColumnName("idPaciente");

                    b.HasKey("IdMedPac")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdPaciente" }, "FK_medicospacientes_pacientes");

                    b.HasIndex(new[] { "IdMedico", "IdPaciente" }, "idUsuario_idPaciente");

                    b.ToTable("medicospacientes", null, t =>
                        {
                            t.HasComment("Relacion de que medicos pueden editar que pacientes");
                        });
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.MutacionesModel", b =>
                {
                    b.Property<int>("IdMutacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idMutacion");

                    b.Property<DateTime>("FechaCreac")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaUltMod")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre")
                        .HasDefaultValueSql("''");

                    b.HasKey("IdMutacion")
                        .HasName("PRIMARY");

                    b.ToTable("Mutaciones");

                    b.HasData(
                        new
                        {
                            IdMutacion = 1,
                            FechaCreac = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            FechaUltMod = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Mutacion1"
                        },
                        new
                        {
                            IdMutacion = 2,
                            FechaCreac = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            FechaUltMod = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Nombre = "Mutacion2"
                        });
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.PacientesModel", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("idPaciente");

                    b.Property<string>("DescripEnferRaras")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("descripEnferRaras")
                        .HasDefaultValueSql("''");

                    b.Property<string>("EnfermRaras")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("enfermRaras")
                        .HasDefaultValueSql("''");

                    b.Property<string>("Farmaco")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("farmaco");

                    b.Property<DateTime>("FechaCreac")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaDiagnostico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaDiagnostico")
                        .HasDefaultValueSql("curdate()");

                    b.Property<DateTime>("FechaFractalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaFractalidad")
                        .HasDefaultValueSql("curdate()");

                    b.Property<DateTime>("FechaNac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fechaNac")
                        .HasDefaultValueSql("curdate()");

                    b.Property<DateTime>("FechaUltMod")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdEpilepsia")
                        .HasColumnType("int(11)")
                        .HasColumnName("idEpilepsia");

                    b.Property<int?>("IdMutacion")
                        .HasColumnType("int(11)")
                        .HasColumnName("idMutacion");

                    b.Property<int>("MedicoCreador")
                        .HasColumnType("int(11)")
                        .HasColumnName("medicoCreador");

                    b.Property<int>("MedicoUltMod")
                        .HasColumnType("int(11)")
                        .HasColumnName("medicoUltMod");

                    b.Property<string>("NumHistoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('H','M')")
                        .HasColumnName("sexo")
                        .HasDefaultValueSql("'H'");

                    b.Property<int>("Talla")
                        .HasPrecision(20, 6)
                        .HasColumnType("int")
                        .HasColumnName("talla");

                    b.HasKey("IdPaciente")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdMutacion" }, "idMutacion");

                    b.HasIndex(new[] { "IdEpilepsia" }, "idTipoEpilepsia");

                    b.HasIndex(new[] { "MedicoCreador" }, "medicoCreador");

                    b.HasIndex(new[] { "MedicoUltMod" }, "medicoUltMod");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Aspnetuserrole", b =>
                {
                    b.HasOne("WebMedicina.BackEnd.Model.AspnetroleModel", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUserRoles_AspNetRoles_RoleId");

                    b.HasOne("WebMedicina.BackEnd.Model.AspnetuserModel", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUserRoles_AspNetUsers_UserId");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.AspnetroleclaimModel", b =>
                {
                    b.HasOne("WebMedicina.BackEnd.Model.AspnetroleModel", "Role")
                        .WithMany("Aspnetroleclaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AspNetRoleClaims_AspNetRoles_RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.Aspnetuserclaim", b =>
                {
                    b.HasOne("WebMedicina.BackEnd.Model.AspnetuserModel", "User")
                        .WithMany("Aspnetuserclaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUserClaims_AspNetUsers_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.Aspnetuserlogin", b =>
                {
                    b.HasOne("WebMedicina.BackEnd.Model.AspnetuserModel", "User")
                        .WithMany("Aspnetuserlogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUserLogins_AspNetUsers_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.AspnetusertokenModel", b =>
                {
                    b.HasOne("WebMedicina.BackEnd.Model.AspnetuserModel", "User")
                        .WithMany("Aspnetusertokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUserTokens_AspNetUsers_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.DatosEvoluEtapasLT", b =>
                {
                    b.HasOne("WebMedicina.BackEnd.Model.EtapaLT", "EtapaLT")
                        .WithMany()
                        .HasForeignKey("EtapaLTId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMedicina.BackEnd.Model.PacientesModel", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteIdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EtapaLT");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.EtapaLT", b =>
                {
                    b.HasOne("WebMedicina.BackEnd.Model.MedicosModel", "MedicoCreador")
                        .WithMany()
                        .HasForeignKey("MedicoCreadorIdMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMedicina.BackEnd.Model.MedicosModel", "MedicoUltModif")
                        .WithMany()
                        .HasForeignKey("MedicoUltModifIdMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicoCreador");

                    b.Navigation("MedicoUltModif");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.EvolucionLT", b =>
                {
                    b.HasOne("WebMedicina.BackEnd.Model.EtapaLT", "EtapasLT")
                        .WithMany()
                        .HasForeignKey("EtapasLTId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebMedicina.BackEnd.Model.MedicosModel", "MedicoUltModif")
                        .WithMany()
                        .HasForeignKey("MedicoUltModifIdMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EtapasLT");

                    b.Navigation("MedicoUltModif");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.MedicosModel", b =>
                {
                    b.HasOne("WebMedicina.BackEnd.Model.AspnetuserModel", "Netuser")
                        .WithMany("Medicos")
                        .HasForeignKey("NetuserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_medicos_aspnetusers");

                    b.Navigation("Netuser");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.MedicospacienteModel", b =>
                {
                    b.HasOne("WebMedicina.BackEnd.Model.MedicosModel", "IdMedicoNavigation")
                        .WithMany("Medicospacientes")
                        .HasForeignKey("IdMedico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_medicospacientes_medicos");

                    b.HasOne("WebMedicina.BackEnd.Model.PacientesModel", "IdPacienteNavigation")
                        .WithMany("Medicospacientes")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_medicospacientes_pacientes");

                    b.Navigation("IdMedicoNavigation");

                    b.Navigation("IdPacienteNavigation");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.PacientesModel", b =>
                {
                    b.HasOne("WebMedicina.BackEnd.Model.EpilepsiaModel", "IdEpilepsiaNavigation")
                        .WithMany("Pacientes")
                        .HasForeignKey("IdEpilepsia")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_pacientes_epilepsias");

                    b.HasOne("WebMedicina.BackEnd.Model.MutacionesModel", "IdMutacionNavigation")
                        .WithMany("Pacientes")
                        .HasForeignKey("IdMutacion")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_pacientes_mutaciones");

                    b.HasOne("WebMedicina.BackEnd.Model.MedicosModel", "MedicoCreadorNavigation")
                        .WithMany("PacienteMedicoCreadorNavigations")
                        .HasForeignKey("MedicoCreador")
                        .IsRequired()
                        .HasConstraintName("FK_pacientes_medicos_2");

                    b.HasOne("WebMedicina.BackEnd.Model.MedicosModel", "MedicoUltModNavigation")
                        .WithMany("PacienteMedicoUltModNavigations")
                        .HasForeignKey("MedicoUltMod")
                        .IsRequired()
                        .HasConstraintName("FK_pacientes_medicos");

                    b.Navigation("IdEpilepsiaNavigation");

                    b.Navigation("IdMutacionNavigation");

                    b.Navigation("MedicoCreadorNavigation");

                    b.Navigation("MedicoUltModNavigation");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.AspnetroleModel", b =>
                {
                    b.Navigation("Aspnetroleclaims");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.AspnetuserModel", b =>
                {
                    b.Navigation("Aspnetuserclaims");

                    b.Navigation("Aspnetuserlogins");

                    b.Navigation("Aspnetusertokens");

                    b.Navigation("Medicos");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.EpilepsiaModel", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.MedicosModel", b =>
                {
                    b.Navigation("Medicospacientes");

                    b.Navigation("PacienteMedicoCreadorNavigations");

                    b.Navigation("PacienteMedicoUltModNavigations");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.MutacionesModel", b =>
                {
                    b.Navigation("Pacientes");
                });

            modelBuilder.Entity("WebMedicina.BackEnd.Model.PacientesModel", b =>
                {
                    b.Navigation("Medicospacientes");
                });
#pragma warning restore 612, 618
        }
    }
}
